project_id = "bxavfvznpfugnkjakygl"

[functions.process-punch]
verify_jwt = false

[functions.send-sms]
verify_jwt = true

[functions.sync-device]
verify_jwt = true

[functions.create-super-admin]
verify_jwt = false
